//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.ExecutePendingCalculations
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationByCropIrrigationWeather
    {
        public long CalculationByCropIrrigationWeatherId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsCompleted { get; set; }
        public string Application { get; set; }
        public string Details { get; set; }
        public long CropIrrigationWeatherId { get; set; }
        public bool IsExecuting { get; set; }
    }
}
