//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.ExecutePendingCalculations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public long StatusId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfReference { get; set; }
        public int WebStatus { get; set; }
        public string Description { get; set; }
    }
}
