//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWeatherInfoService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IrrigationAdvisorEntities : DbContext
    {
        public IrrigationAdvisorEntities()
            : base("name=IrrigationAdvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WeatherData> WeatherDatas { get; set; }
        public virtual DbSet<WeatherStation> WeatherStations { get; set; }
    }
}
