//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWeatherInfoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherStation()
        {
            this.WeatherDatas = new HashSet<WeatherData>();
        }
    
        public long WeatherStationId { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public int StationType { get; set; }
        public System.DateTime DateOfInstallation { get; set; }
        public System.DateTime DateOfService { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int WirelessTransmission { get; set; }
        public long PositionId { get; set; }
        public bool GiveET { get; set; }
        public int WeatherDataType { get; set; }
        public string WebAddress { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherData> WeatherDatas { get; set; }
    }
}
