//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoblueWeatherService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeteoblueWeatherData
    {
        public long MeteoblueWeatherDataId { get; set; }
        public long WeatherStationId { get; set; }
        public System.DateTime WeatherDate { get; set; }
        public Nullable<int> UvIndex { get; set; }
        public decimal TemperatureMax { get; set; }
        public decimal TemperatureMin { get; set; }
        public decimal TemperatureMean { get; set; }
        public decimal FeltTemperatureMax { get; set; }
        public decimal FeltTemperatureMin { get; set; }
        public int WindDirection { get; set; }
        public decimal PrecipitationProbability { get; set; }
        public decimal Rainspot { get; set; }
        public int PredictabilityClass { get; set; }
        public int Predictability { get; set; }
        public decimal Precipitation { get; set; }
        public decimal SnowFraction { get; set; }
        public int SealevelPressureMax { get; set; }
        public int SealevelPressureMin { get; set; }
        public int SealevelPressureMean { get; set; }
        public decimal WindSpeedMax { get; set; }
        public decimal WindSpeedMean { get; set; }
        public decimal WindSpeedMin { get; set; }
        public int RelativeHumidityMax { get; set; }
        public int RelativeHumidityMin { get; set; }
        public int RelativehumidityMean { get; set; }
        public decimal ConvectivePrecipitation { get; set; }
        public decimal PrecipitationHours { get; set; }
        public decimal HumidityGreater90Hours { get; set; }
        public decimal SoilTemperatureMax { get; set; }
        public decimal SoilTemperatureMin { get; set; }
        public decimal SoilTemperatureMean { get; set; }
        public decimal SoilMoistureMax { get; set; }
        public decimal SoilMoistureMin { get; set; }
        public decimal SoilMoistureMean { get; set; }
        public decimal SkinTemperatureMax { get; set; }
        public decimal SkinTemperatureMin { get; set; }
        public decimal SkinTemperatureMean { get; set; }
        public decimal Evapotranspiration { get; set; }
        public decimal LeafWetnessIndex { get; set; }
        public decimal PotentialEvapotranspiration { get; set; }
        public decimal DewPointTemperatureMax { get; set; }
        public decimal DewPointTemperatureMin { get; set; }
        public decimal DewPointTemperatureMean { get; set; }
        public decimal ReferenceEvapotranspirationFao { get; set; }
        public decimal SensibleHeatFlux { get; set; }
    }
}
