//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoblueWeatherService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherStation
    {
        public long WeatherStationId { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public int StationType { get; set; }
        public System.DateTime DateOfInstallation { get; set; }
        public System.DateTime DateOfService { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int WirelessTransmission { get; set; }
        public long PositionId { get; set; }
        public bool GiveET { get; set; }
        public int WeatherDataType { get; set; }
        public string WebAddress { get; set; }
    }
}
