// <auto-generated />
namespace IrrigationAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prueba32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prueba32));
        
        string IMigrationMetadata.Id
        {
            get { return "201810020038289_prueba32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
