// <auto-generated />
namespace IrrigationAdvisor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClosedFeaturesWeb20181103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClosedFeaturesWeb20181103));
        
        string IMigrationMetadata.Id
        {
            get { return "201811032011450_ClosedFeaturesWeb20181103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
