//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.ConfirmIrrigationAdvices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IrrigationAdvisorEntities : DbContext
    {
        public IrrigationAdvisorEntities()
            : base("name=IrrigationAdvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailyRecord> DailyRecords { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<FarmContact> FarmContacts { get; set; }
        public virtual DbSet<Irrigation> Irrigations { get; set; }
        public virtual DbSet<WaterInput> WaterInputs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<CropIrrigationWeather> CropIrrigationWeathers { get; set; }
        public virtual DbSet<IrrigationUnit> IrrigationUnits { get; set; }
    }
}
