//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.ConstantSyncronization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfigurationManagerEntities : DbContext
    {
        public ConfigurationManagerEntities()
            : base("name=ConfigurationManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DecimalValues> DecimalValues { get; set; }
        public virtual DbSet<IntegerValues> IntegerValues { get; set; }
        public virtual DbSet<StringValues> StringValues { get; set; }
        public virtual DbSet<EnumValues> EnumValues { get; set; }
    }
}
