//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.ConstantSyncronization
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumValues
    {
        public int EnumValuesId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string LastModificationBy { get; set; }
    }
}
