//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigurationManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegerValues
    {
        public int IntegerValuesId { get; set; }
        public string Name { get; set; }
        public long Value { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string LastModificationBy { get; set; }
    }
}
