//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crop()
        {
            this.CropIrrigationWeathers = new HashSet<CropIrrigationWeather>();
            this.PhenologicalStages = new HashSet<PhenologicalStage>();
            this.Stages = new HashSet<Stage>();
        }
    
        public long CropId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public long RegionId { get; set; }
        public long SpecieId { get; set; }
        public long CropCoefficientId { get; set; }
        public double MaxEvapotranspirationToIrrigate { get; set; }
        public double MinEvapotranspirationToIrrigate { get; set; }
        public long StopIrrigationStageId { get; set; }
        public Nullable<long> StopIrrigationStage_StageId { get; set; }
        public long MinStageToConsiderETinHBCalculationId { get; set; }
        public Nullable<long> MinStageToConsiderETinHBCalculation_StageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CropIrrigationWeather> CropIrrigationWeathers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhenologicalStage> PhenologicalStages { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Stage Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stages { get; set; }
    }
}
