//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.IrrigationUnits = new HashSet<IrrigationUnit>();
            this.UserFarms = new HashSet<UserFarm>();
        }
    
        public long FarmId { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public long PositionId { get; set; }
        public int Has { get; set; }
        public long WeatherStationId { get; set; }
        public long CityId { get; set; }
        public bool IrrigationUnitReportShowTemperature { get; set; }
        public bool IrrigationUnitReportShowEvapotranspiration { get; set; }
        public bool IrrigationUnitReportShowAvailableWater { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IrrigationUnit> IrrigationUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFarm> UserFarms { get; set; }
    }
}
