//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IrrigationAdvisorWebApiEntities1 : DbContext
    {
        public IrrigationAdvisorWebApiEntities1()
            : base("name=IrrigationAdvisorWebApiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<CropIrrigationWeather> CropIrrigationWeathers { get; set; }
        public virtual DbSet<DailyRecord> DailyRecords { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Irrigation> Irrigations { get; set; }
        public virtual DbSet<IrrigationUnit> IrrigationUnits { get; set; }
        public virtual DbSet<PhenologicalStage> PhenologicalStages { get; set; }
        public virtual DbSet<Rain> Rains { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccess> UserAccesses { get; set; }
        public virtual DbSet<UserFarm> UserFarms { get; set; }
        public virtual DbSet<WaterInput> WaterInputs { get; set; }
        public virtual DbSet<WaterOutput> WaterOutputs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
    }
}
