//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhenologicalStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhenologicalStage()
        {
            this.CropIrrigationWeathers = new HashSet<CropIrrigationWeather>();
            this.DailyRecords = new HashSet<DailyRecord>();
        }
    
        public long PhenologicalStageId { get; set; }
        public long SpecieId { get; set; }
        public long StageId { get; set; }
        public double MinDegree { get; set; }
        public double MaxDegree { get; set; }
        public double RootDepth { get; set; }
        public double HydricBalanceDepth { get; set; }
        public Nullable<long> CropInformationByDate_CropInformationByDateId { get; set; }
        public Nullable<long> Crop_CropId { get; set; }
        public double Coefficient { get; set; }
    
        public virtual Crop Crop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CropIrrigationWeather> CropIrrigationWeathers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyRecord> DailyRecords { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
