//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrrigationAdvisor.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public long UserAccessId { get; set; }
        public System.DateTime LogInDate { get; set; }
        public Nullable<System.DateTime> LogOutDate { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
